// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcFDZZoJOXf-YZOYlMQBKd_Y6AAlXeIUc',
    appId: '1:755981213968:web:8f80a36bdc47de957b8595',
    messagingSenderId: '755981213968',
    projectId: 'assignment-7d04d',
    authDomain: 'assignment-7d04d.firebaseapp.com',
    storageBucket: 'assignment-7d04d.appspot.com',
    measurementId: 'G-LKPQVXKTC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD712t3edmY1cSJEldiBJT1xJQ3LRqT9K8',
    appId: '1:755981213968:android:136aa2488379ccae7b8595',
    messagingSenderId: '755981213968',
    projectId: 'assignment-7d04d',
    storageBucket: 'assignment-7d04d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdTAwqRuNbdgI-n3lzVV98FnZWbLQO9Jg',
    appId: '1:755981213968:ios:769dcac8f05aa2117b8595',
    messagingSenderId: '755981213968',
    projectId: 'assignment-7d04d',
    storageBucket: 'assignment-7d04d.appspot.com',
    iosClientId: '755981213968-r0c77a043pgvoo81f33lvsl9rlhns8cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment01135',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdTAwqRuNbdgI-n3lzVV98FnZWbLQO9Jg',
    appId: '1:755981213968:ios:769dcac8f05aa2117b8595',
    messagingSenderId: '755981213968',
    projectId: 'assignment-7d04d',
    storageBucket: 'assignment-7d04d.appspot.com',
    iosClientId: '755981213968-r0c77a043pgvoo81f33lvsl9rlhns8cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment01135',
  );
}
